
/***********************************************************************
 * @file      irq.c
 * @version   0.1
 * @brief     Function header/interface file.
 *
 * @author    Damini Gowda, damini.gowda@colorado.edu
 * @date      Jan 26, 2025
 *
 *
 * @institution University of Colorado Boulder (UCB)
 * @course      ECEN 5823-001: IoT Embedded Firmware
 * @instructor  Chris Choi
 *
 * @assignment Assignment 2 - Managing Energy Modes
 * @due
 *
 * @resources EFR32xG13 Wireless GeckoReference Manual, Lecture PDFs and reading references
 *
 */

#include <src/irq.h>
#include "em_letimer.h"
#include "em_gpio.h"
#include "src/gpio.h"
#include "src/timers.h"
#include "app.h"
#include "src/scheduler.h"
#include "src/i2c.h"

#define INCLUDE_LOG_DEBUG   1
#include "src/log.h"

static volatile uint32_t leCounter = 0;

/**
 * @brief Interrupt Service Routine (ISR) for LETIMER0.
 *
 * This function handles the interrupts generated by LETIMER0. It checks
 * the flags for COMP0, COMP1, and Underflow events, clears the corresponding
 * interrupt flags, and takes action based on the event. For example, it
 * controls the state of an LED connected to the GPIO pins.
 *
 * - When the COMP0 interrupt is triggered, the LED is turned off, and
 *   the COMP1 interrupt is enabled.
 * - When the COMP1 interrupt is triggered, the LED is turned on, and
 *   the COMP1 interrupt is disabled.
 * - The Underflow interrupt can be used
 *   for additional actions when the timer underflows.
 */
void LETIMER0_IRQHandler(void)
{

  //Check which IF is set
  uint32_t flags = LETIMER_IntGetEnabled(LETIMER0);

  // Clear the interrupt
  LETIMER_IntClear(LETIMER0, flags);

  // Handle Underflow (UF) event, if necessary
  if(flags == LETIMER_IEN_UF){
     leCounter++;
     schedulerSetEventUF();
  }

  if(flags == LETIMER_IEN_COMP1){
      schedulerSetEventCOMP1();
    }
}

/**
 * @brief Get the elapsed time in milliseconds from the LETIMER.
 *
 * This function calculates the elapsed time in milliseconds using the LETIMER
 * counter and period values.
 *
 * @return uint32_t Elapsed time in milliseconds.
 */
uint32_t letimerMilliseconds(void){

  uint32_t ret = 0;

  ret = (leCounter*LETIMER_PERIOD_MS) + (LETIMER_CounterGet(LETIMER0)/COUNT_PER_US);

  return ret;
}

void GPIO_EVEN_IRQHandler(void) {
    uint32_t flags = GPIO_IntGet();
    GPIO_IntClear(flags);

    if (flags & (1 << PB0_PIN)) {
        schedulerSetEventPB0();
    }
}
